// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: arrays.proto

package dev.resteasy.grpc.arrays;

public final class Array_proto {
    private Array_proto() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface dev_resteasy_grpc_arrays___ArrayHolderOrBuilder extends
            // @@protoc_insertion_point(interface_extends:dev_resteasy_grpc_arrays___ArrayHolder)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>string componentClass = 1;</code>
         *
         * @return The componentClass.
         */
        java.lang.String getComponentClass();

        /**
         * <code>string componentClass = 1;</code>
         *
         * @return The bytes for componentClass.
         */
        com.google.protobuf.ByteString getComponentClassBytes();

        /**
         * <code>bool bottom = 2;</code>
         *
         * @return The bottom.
         */
        boolean getBottom();

        /**
         * <code>repeated .google.protobuf.Any google_protobuf_Any_field = 3;</code>
         */
        java.util.List<com.google.protobuf.Any> getGoogleProtobufAnyFieldList();

        /**
         * <code>repeated .google.protobuf.Any google_protobuf_Any_field = 3;</code>
         */
        com.google.protobuf.Any getGoogleProtobufAnyField(int index);

        /**
         * <code>repeated .google.protobuf.Any google_protobuf_Any_field = 3;</code>
         */
        int getGoogleProtobufAnyFieldCount();

        /**
         * <code>repeated .google.protobuf.Any google_protobuf_Any_field = 3;</code>
         */
        java.util.List<? extends com.google.protobuf.AnyOrBuilder> getGoogleProtobufAnyFieldOrBuilderList();

        /**
         * <code>repeated .google.protobuf.Any google_protobuf_Any_field = 3;</code>
         */
        com.google.protobuf.AnyOrBuilder getGoogleProtobufAnyFieldOrBuilder(
                int index);
    }

    /**
     * Protobuf type {@code dev_resteasy_grpc_arrays___ArrayHolder}
     */
    public static final class dev_resteasy_grpc_arrays___ArrayHolder extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:dev_resteasy_grpc_arrays___ArrayHolder)
            dev_resteasy_grpc_arrays___ArrayHolderOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use dev_resteasy_grpc_arrays___ArrayHolder.newBuilder() to construct.
        private dev_resteasy_grpc_arrays___ArrayHolder(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private dev_resteasy_grpc_arrays___ArrayHolder() {
            componentClass_ = "";
            googleProtobufAnyField_ = java.util.Collections.emptyList();
        }

        @java.lang.Override
        @SuppressWarnings({ "unused" })
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new dev_resteasy_grpc_arrays___ArrayHolder();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
            return this.unknownFields;
        }

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return dev.resteasy.grpc.arrays.Array_proto.internal_static_dev_resteasy_grpc_arrays_dev_resteasy_grpc_arrays___ArrayHolder_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
            return dev.resteasy.grpc.arrays.Array_proto.internal_static_dev_resteasy_grpc_arrays_dev_resteasy_grpc_arrays___ArrayHolder_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            dev.resteasy.grpc.arrays.Array_proto.dev_resteasy_grpc_arrays___ArrayHolder.class,
                            dev.resteasy.grpc.arrays.Array_proto.dev_resteasy_grpc_arrays___ArrayHolder.Builder.class);
        }

        public static final int COMPONENTCLASS_FIELD_NUMBER = 1;
        private volatile java.lang.Object componentClass_;

        /**
         * <code>string componentClass = 1;</code>
         *
         * @return The componentClass.
         */
        @java.lang.Override
        public java.lang.String getComponentClass() {
            java.lang.Object ref = componentClass_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                componentClass_ = s;
                return s;
            }
        }

        /**
         * <code>string componentClass = 1;</code>
         *
         * @return The bytes for componentClass.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString getComponentClassBytes() {
            java.lang.Object ref = componentClass_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
                componentClass_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int BOTTOM_FIELD_NUMBER = 2;
        private boolean bottom_;

        /**
         * <code>bool bottom = 2;</code>
         *
         * @return The bottom.
         */
        @java.lang.Override
        public boolean getBottom() {
            return bottom_;
        }

        public static final int GOOGLE_PROTOBUF_ANY_FIELD_FIELD_NUMBER = 3;
        private java.util.List<com.google.protobuf.Any> googleProtobufAnyField_;

        /**
         * <code>repeated .google.protobuf.Any google_protobuf_Any_field = 3;</code>
         */
        @java.lang.Override
        public java.util.List<com.google.protobuf.Any> getGoogleProtobufAnyFieldList() {
            return googleProtobufAnyField_;
        }

        /**
         * <code>repeated .google.protobuf.Any google_protobuf_Any_field = 3;</code>
         */
        @java.lang.Override
        public java.util.List<? extends com.google.protobuf.AnyOrBuilder> getGoogleProtobufAnyFieldOrBuilderList() {
            return googleProtobufAnyField_;
        }

        /**
         * <code>repeated .google.protobuf.Any google_protobuf_Any_field = 3;</code>
         */
        @java.lang.Override
        public int getGoogleProtobufAnyFieldCount() {
            return googleProtobufAnyField_.size();
        }

        /**
         * <code>repeated .google.protobuf.Any google_protobuf_Any_field = 3;</code>
         */
        @java.lang.Override
        public com.google.protobuf.Any getGoogleProtobufAnyField(int index) {
            return googleProtobufAnyField_.get(index);
        }

        /**
         * <code>repeated .google.protobuf.Any google_protobuf_Any_field = 3;</code>
         */
        @java.lang.Override
        public com.google.protobuf.AnyOrBuilder getGoogleProtobufAnyFieldOrBuilder(
                int index) {
            return googleProtobufAnyField_.get(index);
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1)
                return true;
            if (isInitialized == 0)
                return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(componentClass_)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, componentClass_);
            }
            if (bottom_ != false) {
                output.writeBool(2, bottom_);
            }
            for (int i = 0; i < googleProtobufAnyField_.size(); i++) {
                output.writeMessage(3, googleProtobufAnyField_.get(i));
            }
            getUnknownFields().writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1)
                return size;

            size = 0;
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(componentClass_)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, componentClass_);
            }
            if (bottom_ != false) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBoolSize(2, bottom_);
            }
            for (int i = 0; i < googleProtobufAnyField_.size(); i++) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(3, googleProtobufAnyField_.get(i));
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof dev.resteasy.grpc.arrays.Array_proto.dev_resteasy_grpc_arrays___ArrayHolder)) {
                return super.equals(obj);
            }
            dev.resteasy.grpc.arrays.Array_proto.dev_resteasy_grpc_arrays___ArrayHolder other = (dev.resteasy.grpc.arrays.Array_proto.dev_resteasy_grpc_arrays___ArrayHolder) obj;

            if (!getComponentClass()
                    .equals(other.getComponentClass()))
                return false;
            if (getBottom() != other.getBottom())
                return false;
            if (!getGoogleProtobufAnyFieldList()
                    .equals(other.getGoogleProtobufAnyFieldList()))
                return false;
            if (!getUnknownFields().equals(other.getUnknownFields()))
                return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + COMPONENTCLASS_FIELD_NUMBER;
            hash = (53 * hash) + getComponentClass().hashCode();
            hash = (37 * hash) + BOTTOM_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
                    getBottom());
            if (getGoogleProtobufAnyFieldCount() > 0) {
                hash = (37 * hash) + GOOGLE_PROTOBUF_ANY_FIELD_FIELD_NUMBER;
                hash = (53 * hash) + getGoogleProtobufAnyFieldList().hashCode();
            }
            hash = (29 * hash) + getUnknownFields().hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static dev_resteasy_grpc_arrays___ArrayHolder parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static dev_resteasy_grpc_arrays___ArrayHolder parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static dev_resteasy_grpc_arrays___ArrayHolder parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static dev_resteasy_grpc_arrays___ArrayHolder parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static dev_resteasy_grpc_arrays___ArrayHolder parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static dev_resteasy_grpc_arrays___ArrayHolder parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static dev_resteasy_grpc_arrays___ArrayHolder parseFrom(
                java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static dev_resteasy_grpc_arrays___ArrayHolder parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static dev_resteasy_grpc_arrays___ArrayHolder parseDelimitedFrom(
                java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static dev_resteasy_grpc_arrays___ArrayHolder parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static dev_resteasy_grpc_arrays___ArrayHolder parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static dev_resteasy_grpc_arrays___ArrayHolder parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(
                dev.resteasy.grpc.arrays.Array_proto.dev_resteasy_grpc_arrays___ArrayHolder prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder()
                    : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code dev_resteasy_grpc_arrays___ArrayHolder}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:dev_resteasy_grpc_arrays___ArrayHolder)
                dev.resteasy.grpc.arrays.Array_proto.dev_resteasy_grpc_arrays___ArrayHolderOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return dev.resteasy.grpc.arrays.Array_proto.internal_static_dev_resteasy_grpc_arrays_dev_resteasy_grpc_arrays___ArrayHolder_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
                return dev.resteasy.grpc.arrays.Array_proto.internal_static_dev_resteasy_grpc_arrays_dev_resteasy_grpc_arrays___ArrayHolder_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                dev.resteasy.grpc.arrays.Array_proto.dev_resteasy_grpc_arrays___ArrayHolder.class,
                                dev.resteasy.grpc.arrays.Array_proto.dev_resteasy_grpc_arrays___ArrayHolder.Builder.class);
            }

            // Construct using dev.resteasy.grpc.arrays.Array_proto.dev_resteasy_grpc_arrays___ArrayHolder.newBuilder()
            private Builder() {

            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);

            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                componentClass_ = "";

                bottom_ = false;

                if (googleProtobufAnyFieldBuilder_ == null) {
                    googleProtobufAnyField_ = java.util.Collections.emptyList();
                } else {
                    googleProtobufAnyField_ = null;
                    googleProtobufAnyFieldBuilder_.clear();
                }
                bitField0_ = (bitField0_ & ~0x00000001);
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                return dev.resteasy.grpc.arrays.Array_proto.internal_static_dev_resteasy_grpc_arrays_dev_resteasy_grpc_arrays___ArrayHolder_descriptor;
            }

            @java.lang.Override
            public dev_resteasy_grpc_arrays___ArrayHolder getDefaultInstanceForType() {
                return dev.resteasy.grpc.arrays.Array_proto.dev_resteasy_grpc_arrays___ArrayHolder.getDefaultInstance();
            }

            @java.lang.Override
            public dev_resteasy_grpc_arrays___ArrayHolder build() {
                dev.resteasy.grpc.arrays.Array_proto.dev_resteasy_grpc_arrays___ArrayHolder result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public dev_resteasy_grpc_arrays___ArrayHolder buildPartial() {
                dev.resteasy.grpc.arrays.Array_proto.dev_resteasy_grpc_arrays___ArrayHolder result = new dev.resteasy.grpc.arrays.Array_proto.dev_resteasy_grpc_arrays___ArrayHolder(
                        this);
                int from_bitField0_ = bitField0_;
                result.componentClass_ = componentClass_;
                result.bottom_ = bottom_;
                if (googleProtobufAnyFieldBuilder_ == null) {
                    if (((bitField0_ & 0x00000001) != 0)) {
                        googleProtobufAnyField_ = java.util.Collections.unmodifiableList(googleProtobufAnyField_);
                        bitField0_ = (bitField0_ & ~0x00000001);
                    }
                    result.googleProtobufAnyField_ = googleProtobufAnyField_;
                } else {
                    result.googleProtobufAnyField_ = googleProtobufAnyFieldBuilder_.build();
                }
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof dev.resteasy.grpc.arrays.Array_proto.dev_resteasy_grpc_arrays___ArrayHolder) {
                    return mergeFrom((dev.resteasy.grpc.arrays.Array_proto.dev_resteasy_grpc_arrays___ArrayHolder) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(dev.resteasy.grpc.arrays.Array_proto.dev_resteasy_grpc_arrays___ArrayHolder other) {
                if (other == dev.resteasy.grpc.arrays.Array_proto.dev_resteasy_grpc_arrays___ArrayHolder.getDefaultInstance())
                    return this;
                if (!other.getComponentClass().isEmpty()) {
                    componentClass_ = other.componentClass_;
                    onChanged();
                }
                if (other.getBottom() != false) {
                    setBottom(other.getBottom());
                }
                if (googleProtobufAnyFieldBuilder_ == null) {
                    if (!other.googleProtobufAnyField_.isEmpty()) {
                        if (googleProtobufAnyField_.isEmpty()) {
                            googleProtobufAnyField_ = other.googleProtobufAnyField_;
                            bitField0_ = (bitField0_ & ~0x00000001);
                        } else {
                            ensureGoogleProtobufAnyFieldIsMutable();
                            googleProtobufAnyField_.addAll(other.googleProtobufAnyField_);
                        }
                        onChanged();
                    }
                } else {
                    if (!other.googleProtobufAnyField_.isEmpty()) {
                        if (googleProtobufAnyFieldBuilder_.isEmpty()) {
                            googleProtobufAnyFieldBuilder_.dispose();
                            googleProtobufAnyFieldBuilder_ = null;
                            googleProtobufAnyField_ = other.googleProtobufAnyField_;
                            bitField0_ = (bitField0_ & ~0x00000001);
                            googleProtobufAnyFieldBuilder_ = com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders
                                    ? getGoogleProtobufAnyFieldFieldBuilder()
                                    : null;
                        } else {
                            googleProtobufAnyFieldBuilder_.addAllMessages(other.googleProtobufAnyField_);
                        }
                    }
                }
                this.mergeUnknownFields(other.getUnknownFields());
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                if (extensionRegistry == null) {
                    throw new java.lang.NullPointerException();
                }
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                done = true;
                                break;
                            case 10: {
                                componentClass_ = input.readStringRequireUtf8();

                                break;
                            } // case 10
                            case 16: {
                                bottom_ = input.readBool();

                                break;
                            } // case 16
                            case 26: {
                                com.google.protobuf.Any m = input.readMessage(
                                        com.google.protobuf.Any.parser(),
                                        extensionRegistry);
                                if (googleProtobufAnyFieldBuilder_ == null) {
                                    ensureGoogleProtobufAnyFieldIsMutable();
                                    googleProtobufAnyField_.add(m);
                                } else {
                                    googleProtobufAnyFieldBuilder_.addMessage(m);
                                }
                                break;
                            } // case 26
                            default: {
                                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                    done = true; // was an endgroup tag
                                }
                                break;
                            } // default:
                        } // switch (tag)
                    } // while (!done)
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.unwrapIOException();
                } finally {
                    onChanged();
                } // finally
                return this;
            }

            private int bitField0_;

            private java.lang.Object componentClass_ = "";

            /**
             * <code>string componentClass = 1;</code>
             *
             * @return The componentClass.
             */
            public java.lang.String getComponentClass() {
                java.lang.Object ref = componentClass_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    componentClass_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string componentClass = 1;</code>
             *
             * @return The bytes for componentClass.
             */
            public com.google.protobuf.ByteString getComponentClassBytes() {
                java.lang.Object ref = componentClass_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
                    componentClass_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string componentClass = 1;</code>
             *
             * @param value The componentClass to set.
             * @return This builder for chaining.
             */
            public Builder setComponentClass(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                componentClass_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string componentClass = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearComponentClass() {

                componentClass_ = getDefaultInstance().getComponentClass();
                onChanged();
                return this;
            }

            /**
             * <code>string componentClass = 1;</code>
             *
             * @param value The bytes for componentClass to set.
             * @return This builder for chaining.
             */
            public Builder setComponentClassBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                componentClass_ = value;
                onChanged();
                return this;
            }

            private boolean bottom_;

            /**
             * <code>bool bottom = 2;</code>
             *
             * @return The bottom.
             */
            @java.lang.Override
            public boolean getBottom() {
                return bottom_;
            }

            /**
             * <code>bool bottom = 2;</code>
             *
             * @param value The bottom to set.
             * @return This builder for chaining.
             */
            public Builder setBottom(boolean value) {

                bottom_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>bool bottom = 2;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearBottom() {

                bottom_ = false;
                onChanged();
                return this;
            }

            private java.util.List<com.google.protobuf.Any> googleProtobufAnyField_ = java.util.Collections.emptyList();

            private void ensureGoogleProtobufAnyFieldIsMutable() {
                if (!((bitField0_ & 0x00000001) != 0)) {
                    googleProtobufAnyField_ = new java.util.ArrayList<com.google.protobuf.Any>(googleProtobufAnyField_);
                    bitField0_ |= 0x00000001;
                }
            }

            private com.google.protobuf.RepeatedFieldBuilderV3<com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> googleProtobufAnyFieldBuilder_;

            /**
             * <code>repeated .google.protobuf.Any google_protobuf_Any_field = 3;</code>
             */
            public java.util.List<com.google.protobuf.Any> getGoogleProtobufAnyFieldList() {
                if (googleProtobufAnyFieldBuilder_ == null) {
                    return java.util.Collections.unmodifiableList(googleProtobufAnyField_);
                } else {
                    return googleProtobufAnyFieldBuilder_.getMessageList();
                }
            }

            /**
             * <code>repeated .google.protobuf.Any google_protobuf_Any_field = 3;</code>
             */
            public int getGoogleProtobufAnyFieldCount() {
                if (googleProtobufAnyFieldBuilder_ == null) {
                    return googleProtobufAnyField_.size();
                } else {
                    return googleProtobufAnyFieldBuilder_.getCount();
                }
            }

            /**
             * <code>repeated .google.protobuf.Any google_protobuf_Any_field = 3;</code>
             */
            public com.google.protobuf.Any getGoogleProtobufAnyField(int index) {
                if (googleProtobufAnyFieldBuilder_ == null) {
                    return googleProtobufAnyField_.get(index);
                } else {
                    return googleProtobufAnyFieldBuilder_.getMessage(index);
                }
            }

            /**
             * <code>repeated .google.protobuf.Any google_protobuf_Any_field = 3;</code>
             */
            public Builder setGoogleProtobufAnyField(
                    int index, com.google.protobuf.Any value) {
                if (googleProtobufAnyFieldBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureGoogleProtobufAnyFieldIsMutable();
                    googleProtobufAnyField_.set(index, value);
                    onChanged();
                } else {
                    googleProtobufAnyFieldBuilder_.setMessage(index, value);
                }
                return this;
            }

            /**
             * <code>repeated .google.protobuf.Any google_protobuf_Any_field = 3;</code>
             */
            public Builder setGoogleProtobufAnyField(
                    int index, com.google.protobuf.Any.Builder builderForValue) {
                if (googleProtobufAnyFieldBuilder_ == null) {
                    ensureGoogleProtobufAnyFieldIsMutable();
                    googleProtobufAnyField_.set(index, builderForValue.build());
                    onChanged();
                } else {
                    googleProtobufAnyFieldBuilder_.setMessage(index, builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .google.protobuf.Any google_protobuf_Any_field = 3;</code>
             */
            public Builder addGoogleProtobufAnyField(com.google.protobuf.Any value) {
                if (googleProtobufAnyFieldBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureGoogleProtobufAnyFieldIsMutable();
                    googleProtobufAnyField_.add(value);
                    onChanged();
                } else {
                    googleProtobufAnyFieldBuilder_.addMessage(value);
                }
                return this;
            }

            /**
             * <code>repeated .google.protobuf.Any google_protobuf_Any_field = 3;</code>
             */
            public Builder addGoogleProtobufAnyField(
                    int index, com.google.protobuf.Any value) {
                if (googleProtobufAnyFieldBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureGoogleProtobufAnyFieldIsMutable();
                    googleProtobufAnyField_.add(index, value);
                    onChanged();
                } else {
                    googleProtobufAnyFieldBuilder_.addMessage(index, value);
                }
                return this;
            }

            /**
             * <code>repeated .google.protobuf.Any google_protobuf_Any_field = 3;</code>
             */
            public Builder addGoogleProtobufAnyField(
                    com.google.protobuf.Any.Builder builderForValue) {
                if (googleProtobufAnyFieldBuilder_ == null) {
                    ensureGoogleProtobufAnyFieldIsMutable();
                    googleProtobufAnyField_.add(builderForValue.build());
                    onChanged();
                } else {
                    googleProtobufAnyFieldBuilder_.addMessage(builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .google.protobuf.Any google_protobuf_Any_field = 3;</code>
             */
            public Builder addGoogleProtobufAnyField(
                    int index, com.google.protobuf.Any.Builder builderForValue) {
                if (googleProtobufAnyFieldBuilder_ == null) {
                    ensureGoogleProtobufAnyFieldIsMutable();
                    googleProtobufAnyField_.add(index, builderForValue.build());
                    onChanged();
                } else {
                    googleProtobufAnyFieldBuilder_.addMessage(index, builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .google.protobuf.Any google_protobuf_Any_field = 3;</code>
             */
            public Builder addAllGoogleProtobufAnyField(
                    java.lang.Iterable<? extends com.google.protobuf.Any> values) {
                if (googleProtobufAnyFieldBuilder_ == null) {
                    ensureGoogleProtobufAnyFieldIsMutable();
                    com.google.protobuf.AbstractMessageLite.Builder.addAll(
                            values, googleProtobufAnyField_);
                    onChanged();
                } else {
                    googleProtobufAnyFieldBuilder_.addAllMessages(values);
                }
                return this;
            }

            /**
             * <code>repeated .google.protobuf.Any google_protobuf_Any_field = 3;</code>
             */
            public Builder clearGoogleProtobufAnyField() {
                if (googleProtobufAnyFieldBuilder_ == null) {
                    googleProtobufAnyField_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000001);
                    onChanged();
                } else {
                    googleProtobufAnyFieldBuilder_.clear();
                }
                return this;
            }

            /**
             * <code>repeated .google.protobuf.Any google_protobuf_Any_field = 3;</code>
             */
            public Builder removeGoogleProtobufAnyField(int index) {
                if (googleProtobufAnyFieldBuilder_ == null) {
                    ensureGoogleProtobufAnyFieldIsMutable();
                    googleProtobufAnyField_.remove(index);
                    onChanged();
                } else {
                    googleProtobufAnyFieldBuilder_.remove(index);
                }
                return this;
            }

            /**
             * <code>repeated .google.protobuf.Any google_protobuf_Any_field = 3;</code>
             */
            public com.google.protobuf.Any.Builder getGoogleProtobufAnyFieldBuilder(
                    int index) {
                return getGoogleProtobufAnyFieldFieldBuilder().getBuilder(index);
            }

            /**
             * <code>repeated .google.protobuf.Any google_protobuf_Any_field = 3;</code>
             */
            public com.google.protobuf.AnyOrBuilder getGoogleProtobufAnyFieldOrBuilder(
                    int index) {
                if (googleProtobufAnyFieldBuilder_ == null) {
                    return googleProtobufAnyField_.get(index);
                } else {
                    return googleProtobufAnyFieldBuilder_.getMessageOrBuilder(index);
                }
            }

            /**
             * <code>repeated .google.protobuf.Any google_protobuf_Any_field = 3;</code>
             */
            public java.util.List<? extends com.google.protobuf.AnyOrBuilder> getGoogleProtobufAnyFieldOrBuilderList() {
                if (googleProtobufAnyFieldBuilder_ != null) {
                    return googleProtobufAnyFieldBuilder_.getMessageOrBuilderList();
                } else {
                    return java.util.Collections.unmodifiableList(googleProtobufAnyField_);
                }
            }

            /**
             * <code>repeated .google.protobuf.Any google_protobuf_Any_field = 3;</code>
             */
            public com.google.protobuf.Any.Builder addGoogleProtobufAnyFieldBuilder() {
                return getGoogleProtobufAnyFieldFieldBuilder().addBuilder(
                        com.google.protobuf.Any.getDefaultInstance());
            }

            /**
             * <code>repeated .google.protobuf.Any google_protobuf_Any_field = 3;</code>
             */
            public com.google.protobuf.Any.Builder addGoogleProtobufAnyFieldBuilder(
                    int index) {
                return getGoogleProtobufAnyFieldFieldBuilder().addBuilder(
                        index, com.google.protobuf.Any.getDefaultInstance());
            }

            /**
             * <code>repeated .google.protobuf.Any google_protobuf_Any_field = 3;</code>
             */
            public java.util.List<com.google.protobuf.Any.Builder> getGoogleProtobufAnyFieldBuilderList() {
                return getGoogleProtobufAnyFieldFieldBuilder().getBuilderList();
            }

            private com.google.protobuf.RepeatedFieldBuilderV3<com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> getGoogleProtobufAnyFieldFieldBuilder() {
                if (googleProtobufAnyFieldBuilder_ == null) {
                    googleProtobufAnyFieldBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                            googleProtobufAnyField_,
                            ((bitField0_ & 0x00000001) != 0),
                            getParentForChildren(),
                            isClean());
                    googleProtobufAnyField_ = null;
                }
                return googleProtobufAnyFieldBuilder_;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }

            // @@protoc_insertion_point(builder_scope:dev_resteasy_grpc_arrays___ArrayHolder)
        }

        // @@protoc_insertion_point(class_scope:dev_resteasy_grpc_arrays___ArrayHolder)
        private static final dev_resteasy_grpc_arrays___ArrayHolder DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new dev.resteasy.grpc.arrays.Array_proto.dev_resteasy_grpc_arrays___ArrayHolder();
        }

        public static dev_resteasy_grpc_arrays___ArrayHolder getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<dev_resteasy_grpc_arrays___ArrayHolder> PARSER = new com.google.protobuf.AbstractParser<dev_resteasy_grpc_arrays___ArrayHolder>() {
            @java.lang.Override
            public dev_resteasy_grpc_arrays___ArrayHolder parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                Builder builder = newBuilder();
                try {
                    builder.mergeFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.setUnfinishedMessage(builder.buildPartial());
                } catch (com.google.protobuf.UninitializedMessageException e) {
                    throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
                } catch (java.io.IOException e) {
                    throw new com.google.protobuf.InvalidProtocolBufferException(e)
                            .setUnfinishedMessage(builder.buildPartial());
                }
                return builder.buildPartial();
            }
        };

        public static com.google.protobuf.Parser<dev_resteasy_grpc_arrays___ArrayHolder> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<dev_resteasy_grpc_arrays___ArrayHolder> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public dev_resteasy_grpc_arrays___ArrayHolder getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor internal_static_dev_resteasy_grpc_arrays_dev_resteasy_grpc_arrays___ArrayHolder_descriptor;
    private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_dev_resteasy_grpc_arrays_dev_resteasy_grpc_arrays___ArrayHolder_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
    static {
        java.lang.String[] descriptorData = {
                "\n\014arrays.proto\022\030dev.resteasy.grpc.arrays" +
                        "\032\031google/protobuf/any.proto\"\211\001\n&dev_rest" +
                        "easy_grpc_arrays___ArrayHolder\022\026\n\016compon" +
                        "entClass\030\001 \001(\t\022\016\n\006bottom\030\002 \001(\010\0227\n\031google" +
                        "_protobuf_Any_field\030\003 \003(\0132\024.google.proto" +
                        "buf.AnyB\'\n\030dev.resteasy.grpc.arraysB\013Arr" +
                        "ay_protob\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {
                                com.google.protobuf.AnyProto.getDescriptor(),
                        });
        internal_static_dev_resteasy_grpc_arrays_dev_resteasy_grpc_arrays___ArrayHolder_descriptor = getDescriptor()
                .getMessageTypes().get(0);
        internal_static_dev_resteasy_grpc_arrays_dev_resteasy_grpc_arrays___ArrayHolder_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_dev_resteasy_grpc_arrays_dev_resteasy_grpc_arrays___ArrayHolder_descriptor,
                new java.lang.String[] { "ComponentClass", "Bottom", "GoogleProtobufAnyField", });
        com.google.protobuf.AnyProto.getDescriptor();
    }

    // @@protoc_insertion_point(outer_class_scope)
}
